name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js for backend
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Run backend tests
        run: npm test --prefix backend

      - name: Build backend Docker image
        run: docker build -t backend:ci ./backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js for frontend
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Run frontend tests
        run: npm test --prefix frontend

      - name: Build frontend Docker image
        run: docker build -t frontend:ci ./frontend
